# Generated by Django 4.0.5 on 2022-09-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=20)),
                ('last_seen_address', models.CharField(max_length=40)),
                ('last_seen_zip_code', models.CharField(max_length=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
