# Generated by Django 4.0.5 on 2022-09-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_missing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missing',
            name='image',
        ),
    ]
