# Generated by Django 4.0.5 on 2022-09-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing',
            name='desc',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
